package ssu2

import (
	"os"
	"path/filepath"

	"github.com/go-i2p/crypto/rand"
	ssu2noise "github.com/go-i2p/go-noise/ssu2"
	"github.com/samber/oops"
)

const (
	// obfuscationIVSize is the size of the SSU2 ChaCha20 obfuscation IV in bytes.
	obfuscationIVSize = 8

	// obfuscationIVFilename is the name of the file storing the obfuscation IV.
	obfuscationIVFilename = "ssu2_obfuscation.dat"

	// introKeySize is the size of the SSU2 introduction key in bytes.
	introKeySize = 32

	// introKeyFilename is the name of the file storing the introduction key.
	introKeyFilename = "ssu2_intro_key.dat"
)

// PersistentConfig manages persistent SSU2 configuration data.
// It handles loading and storing the obfuscation IV and introduction key, both
// of which must remain consistent across router restarts.
type PersistentConfig struct {
	workingDir string
}

// NewPersistentConfig creates a new persistent configuration manager.
// workingDir is the router's working directory (e.g. ~/.go-i2p/config).
func NewPersistentConfig(workingDir string) *PersistentConfig {
	return &PersistentConfig{workingDir: workingDir}
}

// LoadOrGenerateObfuscationIV loads the 8-byte ChaCha20 obfuscation IV from
// persistent storage, or generates and stores a new one if the file is absent.
// Returns an error if the file exists but contains invalid data.
func (pc *PersistentConfig) LoadOrGenerateObfuscationIV() ([]byte, error) {
	ivPath := filepath.Join(pc.workingDir, obfuscationIVFilename)
	log.WithField("iv_path", ivPath).Debug("loading or generating SSU2 obfuscation IV")

	iv, err := pc.loadFile(ivPath, obfuscationIVSize, "obfuscation IV")
	if err == nil {
		log.Debug("loaded existing SSU2 obfuscation IV")
		return iv, nil
	}

	// If the file is present but invalid, propagate the validation error.
	if _, statErr := os.Stat(ivPath); statErr == nil {
		log.WithError(err).Error("SSU2 obfuscation IV file exists but is invalid")
		return nil, err
	}

	log.Info("SSU2 obfuscation IV not found, generating new IV")
	return pc.generateAndStoreKey(ivPath, obfuscationIVSize, "obfuscation IV")
}

// LoadOrGenerateIntroKey loads the 32-byte introduction key from persistent
// storage, or generates and stores a new one if the file is absent.
// Returns an error if the file exists but contains invalid data.
func (pc *PersistentConfig) LoadOrGenerateIntroKey() ([]byte, error) {
	keyPath := filepath.Join(pc.workingDir, introKeyFilename)
	log.WithField("key_path", keyPath).Debug("loading or generating SSU2 intro key")

	key, err := pc.loadFile(keyPath, introKeySize, "intro key")
	if err == nil {
		log.Debug("loaded existing SSU2 intro key")
		return key, nil
	}

	if _, statErr := os.Stat(keyPath); statErr == nil {
		log.WithError(err).Error("SSU2 intro key file exists but is invalid")
		return nil, err
	}

	log.Info("SSU2 intro key not found, generating new key")
	return pc.generateAndStoreKey(keyPath, introKeySize, "intro key")
}

// loadFile reads exactly wantSize bytes from path.
func (pc *PersistentConfig) loadFile(path string, wantSize int, name string) ([]byte, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if len(data) != wantSize {
		return nil, oops.Wrapf(
			ErrInvalidConfig,
			"SSU2 %s file has wrong size: expected %d bytes, got %d",
			name, wantSize, len(data),
		)
	}
	return data, nil
}

// generateAndStoreKey creates a random key of keySize bytes, persists it at
// path with 0600 permissions, and returns the generated bytes.
func (pc *PersistentConfig) generateAndStoreKey(path string, keySize int, name string) ([]byte, error) {
	log.WithField("path", path).Infof("generating new SSU2 %s", name)

	if err := os.MkdirAll(pc.workingDir, 0o755); err != nil {
		log.WithError(err).Error("failed to create config directory")
		return nil, WrapSSU2Error(err, "creating config directory")
	}

	key := make([]byte, keySize)
	if _, err := rand.Read(key); err != nil {
		log.WithError(err).Errorf("failed to generate SSU2 %s", name)
		return nil, WrapSSU2Error(err, "generating "+name)
	}

	if err := os.WriteFile(path, key, 0o600); err != nil {
		log.WithError(err).Errorf("failed to store SSU2 %s", name)
		return nil, WrapSSU2Error(err, "storing "+name)
	}

	log.Infof("generated and stored SSU2 %s", name)
	return key, nil
}

// initKeyManagement sets up the PersistentConfig, loads/generates the intro key
// and obfuscation IV, wires them into ssu2Config, and starts the
// KeyRotationManager for the transport.
func initKeyManagement(t *SSU2Transport, ssu2Config *ssu2noise.SSU2Config) error {
	pc := NewPersistentConfig(t.config.WorkingDir)
	t.persistentConfig = pc

	introKey, err := pc.LoadOrGenerateIntroKey()
	if err != nil {
		return WrapSSU2Error(err, "loading intro key")
	}

	obfuscationIV, err := pc.LoadOrGenerateObfuscationIV()
	if err != nil {
		return WrapSSU2Error(err, "loading obfuscation IV")
	}

	// Apply obfuscation IV to the SSU2Config so new sessions use it.
	ssu2Config.WithChaChaObfuscation(true, obfuscationIV)

	staticKey := ssu2Config.StaticKey
	krm, err := ssu2noise.NewKeyRotationManager(staticKey, introKey, true)
	if err != nil {
		return WrapSSU2Error(err, "creating key rotation manager")
	}

	krm.SetRotationCallback(func(keyType string, oldKey, newKey *ssu2noise.ManagedKey) {
		log.WithFields(map[string]interface{}{
			"key_type": keyType,
		}).Info("SSU2 key rotated")
	})

	krm.Start()
	t.keyRotationManager = krm
	return nil
}

// GetIntroKey returns the current introduction key, or nil if key management is
// not initialised.
func (t *SSU2Transport) GetIntroKey() []byte {
	if t.keyRotationManager == nil {
		return nil
	}
	return t.keyRotationManager.GetIntroKey()
}
